formatter: markdown table
recursive:
  enabled: true
sections:
  hide:
    - requirements
output:
  file: README.md
header-from: ./docs/.header.md
content: |-
  {{ .Header }}

  {{ .Modules }}
  {{ .Providers }}
  {{ .Resources }}
  {{ .Inputs }}
  {{ .Outputs }}

  ## Usage

  ```hcl
  {{ include "docs/.usage.tf" }}
  ```
